<?php

use App\Permission;
use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $permissions = [
            ['title' => 'home_access',],

            ['title' => 'dashboard_access',],

            ['title' => 'statistic_access',],

            ['title' => 'planning_access',],
            ['title' => 'account_create',],
            ['title' => 'account_edit',],
            ['title' => 'account_show',],
            ['title' => 'account_delete',],
            ['title' => 'account_access',],
            ['title' => 'work_group_create',],
            ['title' => 'work_group_edit',],
            ['title' => 'work_group_show',],
            ['title' => 'work_group_delete',],
            ['title' => 'work_group_access',],
            ['title' => 'school_create',],
            ['title' => 'school_edit',],
            ['title' => 'school_show',],
            ['title' => 'school_delete',],
            ['title' => 'school_access',],
            ['title' => 'infrastructure_create',],
            ['title' => 'infrastructure_edit',],
            ['title' => 'infrastructure_show',],
            ['title' => 'infrastructure_delete',],
            ['title' => 'infrastructure_access',],
            ['title' => 'disaster_create',],
            ['title' => 'disaster_edit',],
            ['title' => 'disaster_show',],
            ['title' => 'disaster_delete',],
            ['title' => 'disaster_access',],
            ['title' => 'quality_report_create',],
            ['title' => 'quality_report_edit',],
            ['title' => 'quality_report_show',],
            ['title' => 'quality_report_delete',],
            ['title' => 'quality_report_access',],
            ['title' => 'team_create',],
            ['title' => 'team_edit',],
            ['title' => 'team_show',],
            ['title' => 'team_delete',],
            ['title' => 'team_access',],
            ['title' => 'study_create',],
            ['title' => 'study_edit',],
            ['title' => 'study_show',],
            ['title' => 'study_delete',],
            ['title' => 'study_access',],
            ['title' => 'curriculum_create',],
            ['title' => 'curriculum_edit',],
            ['title' => 'curriculum_show',],
            ['title' => 'curriculum_delete',],
            ['title' => 'curriculum_access',],
            ['title' => 'lesson_plan_create',],
            ['title' => 'lesson_plan_edit',],
            ['title' => 'lesson_plan_show',],
            ['title' => 'lesson_plan_delete',],
            ['title' => 'lesson_plan_access',],
            ['title' => 'budget_plan_create',],
            ['title' => 'budget_plan_edit',],
            ['title' => 'budget_plan_show',],
            ['title' => 'budget_plan_delete',],
            ['title' => 'budget_plan_access',],
            ['title' => 'partner_create',],
            ['title' => 'partner_edit',],
            ['title' => 'partner_show',],
            ['title' => 'partner_delete',],
            ['title' => 'partner_access',],
            ['title' => 'cadre_create',],
            ['title' => 'cadre_edit',],
            ['title' => 'cadre_show',],
            ['title' => 'cadre_delete',],
            ['title' => 'cadre_access',],
            ['title' => 'work_program_create',],
            ['title' => 'work_program_edit',],
            ['title' => 'work_program_show',],
            ['title' => 'work_program_delete',],
            ['title' => 'work_program_access',],
            ['title' => 'innovation_create',],
            ['title' => 'innovation_edit',],
            ['title' => 'innovation_show',],
            ['title' => 'innovation_delete',],
            ['title' => 'innovation_access',],
            ['title' => 'this_year_action_plan_access',],
            ['title' => 'next_year_action_plan_access',],
            ///
            ['title' => 'implementation_activity_access',],
            ['title' => 'cadre_activity_create',],
            ['title' => 'cadre_activity_edit',],
            ['title' => 'cadre_activity_show',],
            ['title' => 'cadre_activity_delete',],
            ['title' => 'cadre_activity_access',],
            ['title' => 'activity_create',],
            ['title' => 'activity_edit',],
            ['title' => 'activity_show',],
            ['title' => 'activity_delete',],
            ['title' => 'activity_access',],
            ['title' => 'activity_implementation_create',],
            ['title' => 'activity_implementation_edit',],
            ['title' => 'activity_implementation_show',],
            ['title' => 'activity_implementation_delete',],
            ['title' => 'activity_implementation_access',],
            ['title' => 'this_year_activity_implementation_access',],
            ['title' => 'next_year_activity_implementation_access',],
            ///
            ['title' => 'monitoring_and_evaluation_access',],
            ['title' => 'monitor_create',],
            ['title' => 'monitor_edit',],
            ['title' => 'monitor_show',],
            ['title' => 'monitor_delete',],
            ['title' => 'monitor_access',],
            ['title' => 'recommendation_create',],
            ['title' => 'recommendation_edit',],
            ['title' => 'recommendation_show',],
            ['title' => 'recommendation_delete',],
            ['title' => 'recommendation_access',],
            ['title' => 'evaluation_create',],
            ['title' => 'evaluation_edit',],
            ['title' => 'evaluation_show',],
            ['title' => 'evaluation_delete',],
            ['title' => 'evaluation_access',],
            ['title' => 'movement_recommendation_create',],
            ['title' => 'movement_recommendation_edit',],
            ['title' => 'movement_recommendation_show',],
            ['title' => 'movement_recommendation_delete',],
            ['title' => 'movement_recommendation_access',],
            ///
            ['title' => 'verification_access',],
            ['title' => 'assessment_create',],
            ['title' => 'assessment_edit',],
            ['title' => 'assessment_show',],
            ['title' => 'assessment_delete',],
            ['title' => 'assessment_access',],
            ['title' => 'assessment_result_access',],
            ['title' => 'assessment_result_verification_access',],
            ///
            ['title' => 'setting_access',],
            ['title' => 'banner_create',],
            ['title' => 'banner_edit',],
            ['title' => 'banner_show',],
            ['title' => 'banner_delete',],
            ['title' => 'banner_access',],
            ['title' => 'province_create',],
            ['title' => 'province_edit',],
            ['title' => 'province_show',],
            ['title' => 'province_delete',],
            ['title' => 'province_access',],
            ['title' => 'city_create',],
            ['title' => 'city_edit',],
            ['title' => 'city_show',],
            ['title' => 'city_delete',],
            ['title' => 'city_access',],
            ['title' => 'disaster_threat_create',],
            ['title' => 'disaster_threat_edit',],
            ['title' => 'disaster_threat_show',],
            ['title' => 'disaster_threat_delete',],
            ['title' => 'disaster_threat_access',],
            ['title' => 'curriculum_calendar_create',],
            ['title' => 'curriculum_calendar_edit',],
            ['title' => 'curriculum_calendar_show',],
            ['title' => 'curriculum_calendar_delete',],
            ['title' => 'curriculum_calendar_access',],
            ///
            ['title' => 'user_management_access',],
            ['title' => 'permission_create',],
            ['title' => 'permission_edit',],
            ['title' => 'permission_show',],
            ['title' => 'permission_delete',],
            ['title' => 'permission_access',],
            ['title' => 'role_create',],
            ['title' => 'role_edit',],
            ['title' => 'role_show',],
            ['title' => 'role_delete',],
            ['title' => 'role_access',],
            ['title' => 'user_create',],
            ['title' => 'user_edit',],
            ['title' => 'user_show',],
            ['title' => 'user_delete',],
            ['title' => 'user_access',],


            ['title' => 'audit_log_show',],
            ['title' => 'audit_log_access',],
            ['title' => 'profile_password_edit',],

        ];

        if (is_array($permissions) && count($permissions)) {
            Permission::query()->insert($permissions);
        }
    }
}
